In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore') #handle_unknown='ignore' is used to handle any unseen categories during transformation. When an unknown category is encountered, the resulting one-hot encoded columns for this feature will be all zeros.
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [6]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [7]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis = 1)
y = data['EstimatedSalary']

In [8]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [10]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)
    
with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [12]:
#build the ANN model
model = Sequential([
    Dense(64, activation = 'relu', input_shape = (X_train.shape[1],)),
    Dense(32, activation = 'relu'),
    Dense(1) #output layer for regression, the activation function is linear activation fun by default for regression. We're not doing anything here with the output(whatever we're getting just using that) because we want the output to be a continuous value, which is suitable for regression tasks.
])

# Compile the model
model.compile(optimizer = 'adam', loss = 'mean_absolute_error', metrics = ['mae'])

model.summary()

c:\Users\TANVI AGARWAL\ANN Classification\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
# Set up TensorBoard
log_dir = 'regressionlogs/fit/' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir = log_dir, histogram_freq = 1)

In [15]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 100376.4766 - mae: 100376.4766 - val_loss: 98510.6484 - val_mae: 98510.6484
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99608.4453 - mae: 99608.4453 - val_loss: 96964.0859 - val_mae: 96964.0859
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 96919.5703 - mae: 96919.5703 - val_loss: 93027.6562 - val_mae: 93027.6562
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 91627.1562 - mae: 91627.1562 - val_loss: 86439.3125 - val_mae: 86439.3125
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 83917.3281 - mae: 83917.3281 - val_loss: 77963.6797 - val_mae: 77963.6797
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 74847.7500 - mae: 74847.7500 - val_loss: 69085.8516 - val_mae: 69085.8516
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 65947.1484 - mae: 65947.1484 - val_loss: 61231.0039 - val_mae: 61231.0039
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 58803.4297 - mae: 58803.4297 - val_loss: 55746.7305 - val_mae: 55746.7305
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 54233.6211 - mae: 54233.6211 - val_loss: 52536.6484 - val_mae: 52536.6484
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 51795.2852 - mae: 51795.2852 - val_loss: 51250.4922 - val_mae: 51250.4922
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50789.0703 - mae: 50789.0703 - val_loss: 50818.7891 - val_mae: 50818.7891
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50416.3203 - mae: 50416.3203 - val_loss: 50672.6602 - val_mae: 50672.6602
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50270.3828 - mae: 50270.3828 - val_loss: 50596.1133 - val_mae: 50596.1133
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50184.4961 - mae: 50184.4961 - val_loss: 50553.3281 - val_mae: 50553.3281
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50123.0508 - mae: 50123.0508 - val_loss: 50522.8945 - val_mae: 50522.8945
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50071.8984 - mae: 50071.8984 - val_loss: 50484.1055 - val_mae: 50484.1055
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50029.3359 - mae: 50029.3359 - val_loss: 50468.4492 - val_mae: 50468.4492
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49992.8477 - mae: 49992.8477 - val_loss: 50445.3281 - val_mae: 50445.3281
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 49956.6836 - mae: 49956.6836 - val_loss: 50414.5859 - val_mae: 50414.5859
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49919.8438 - mae: 49919.8438 - val_loss: 50402.0664 - val_mae: 50402.0664
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49890.3672 - mae: 49890.3672 - val_loss: 50374.1953 - val_mae: 50374.1953
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49859.6406 - mae: 49859.6406 - val_loss: 50356.4961 - val_mae: 50356.4961
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49834.7852 - mae: 49834.7852 - val_loss: 50337.6016 - val_mae: 50337.6016
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49811.1680 - mae: 49811.1680 - val_loss: 50322.4141 - val_mae: 50322.4141
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49787.0117 - mae: 49787.0117 - val_loss: 50311.5781 - val_mae: 50311.5781
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49766.4844 - mae: 49766.4844 - val_loss: 50297.3203 - val_mae: 50297.3203
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49748.2734 - mae: 49748.2734 - val_loss: 50281.3672 - val_mae: 50281.3672
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49725.8828 - mae: 49725.8828 - val_loss: 50267.9023 - val_mae: 50267.9023
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49711.5469 - mae: 49711.5469 - val_loss: 50263.2070 - val_mae: 50263.2070
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49692.4102 - mae: 49692.4102 - val_loss: 50249.7266 - val_mae: 50249.7266
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49677.9219 - mae: 49677.9219 - val_loss: 50255.5547 - val_mae: 50255.5547
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49661.4258 - mae: 49661.4258 - val_loss: 50238.9375 - val_mae: 50238.9375
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49647.3633 - mae: 49647.3633 - val_loss: 50234.4688 - val_mae: 50234.4688
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49634.6445 - mae: 49634.6445 - val_loss: 50241.6484 - val_mae: 50241.6484
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49620.6328 - mae: 49620.6328 - val_loss: 50235.5234 - val_mae: 50235.5234
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49606.0938 - mae: 49606.0938 - val_loss: 50229.0898 - val_mae: 50229.0898
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49592.4102 - mae: 49592.4102 - val_loss: 50218.6523 - val_mae: 50218.6523
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49581.9492 - mae: 49581.9492 - val_loss: 50232.8203 - val_mae: 50232.8203
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49575.6953 - mae: 49575.6953 - val_loss: 50229.2852 - val_mae: 50229.2852
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49560.4453 - mae: 49560.4453 - val_loss: 50232.3789 - val_mae: 50232.3789
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49551.1367 - mae: 49551.1367 - val_loss: 50243.6484 - val_mae: 50243.6484
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49539.9609 - mae: 49539.9609 - val_loss: 50226.3672 - val_mae: 50226.3672
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49530.9141 - mae: 49530.9141 - val_loss: 50228.2344 - val_mae: 50228.2344
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49519.1172 - mae: 49519.1172 - val_loss: 50233.1641 - val_mae: 50233.1641
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49513.0391 - mae: 49513.0391 - val_loss: 50225.9609 - val_mae: 50225.9609
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49505.2656 - mae: 49505.2656 - val_loss: 50235.0430 - val_mae: 50235.0430
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49495.1484 - mae: 49495.1484 - val_loss: 50229.8906 - val_mae: 50229.8906

In [17]:
%load_ext tensorboard

In [19]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 32032), started 0:00:51 ago. (Use '!kill 32032' to kill it.)

In [ ]:
# Evaluate model on the test data
test_loss, test_mae = model.evaluate(X_test, y_test) #model.evaluate() tests the model on unseen data. It returns the loss value and any additional metrics specified during model compilation. In this case, it returns the mean absolute error (MAE) on the test set, which is a common metric for regression tasks.
print(f"Test MAE: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50218.6523 - mae: 50218.6523
Test MAE: 50218.65234375

In [21]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.